name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash --noprofile --norc -xeo pipefail {0}

jobs:

  build_wheel:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install cibuildwheel
        run: python -m pip install -U cibuildwheel

      - name: Build wheels
        env:
          CIBW_BUILD: "cp3?-* cp31?-*"
          CIBW_SKIP: "*-manylinux_i686 *-win32"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_ENVIRONMENT_LINUX: "CFLAGS=-g0 LDFLAGS=-Wl,-strip-debug"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"
          CIBW_BEFORE_TEST: "pip install pytest"
          CIBW_TEST_COMMAND: "pytest {project}/test"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wheels (${{ runner.os }})
          path: wheelhouse/*

  release:

    name: Release
    runs-on: ubuntu-latest
    needs: [build_wheel]
    if: startsWith(github.ref, 'refs/tags/')

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install -U setuptools twine

      - name: Build source distribution
        run: python setup.py sdist

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: wheelhouse

      - name: Publish PyPI release
        env:
          TWINE_NON_INTERACTIVE: 1
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          # Optional: twine will fallback to default if empty.
          TWINE_REPOSITORY_URL: ${{ secrets.PYPI_URL }}
        run: python -m twine upload dist/* wheelhouse/*/*
